name: Build Android APK (Kivy)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev
          pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Init Buildozer
        run: |
          buildozer init
          sed -i 's/title = .*/title = Zummaria Inventory/' buildozer.spec
          sed -i 's/package.name = .*/package.name = zummaria/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.zummaria/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,jpg,png,txt/' buildozer.spec
          sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/source.main = .*/source.main = Jard5.py/' buildozer.spec

          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "android.sdk = 33" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.build_tools_version = 33.0.2" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zummaria-APK
          path: bin/*.apk
